version: "3"

services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entryPoints.web.address=:80
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    command:
      - --provider=github
      - --http-address=0.0.0.0:4180
      - --upstream=http://nodered:1880
      - --cookie-secret=00000000000000000000000000000000
      - --set-xauthrequest=true
    environment:
      - OAUTH2_PROXY_CLIENT_ID=changeme
      - OAUTH2_PROXY_CLIENT_SECRET=changeme

  nodered:
    image: nodered/node-red:latest
    labels:
      - "traefik.http.routers.nodered.rule=PathPrefix(`/`)"
      - "traefik.http.routers.nodered.entrypoints=web"
      - "traefik.http.routers.nodered.middlewares=oauth2-auth"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.http.middlewares.oauth2-auth.forwardauth.address=http://oauth2-proxy:4180/auth"
      - "traefik.http.middlewares.oauth2-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.oauth2-auth.forwardauth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Preferred-Username"
